initStore([
  {
    id: 0,
    title: 'Starfield (Xbox/PC)',
    description: 'Episches Weltraum-Rollenspiel von den Machern.',
    price: 119.95,
    discountPrice: 94.95,
    image: 'images/service-1.jpg',
  },
  {
    id: 1,
    title: 'The Last of Us Part I (PS5)',
    description: 'Neuauflage des gefeierten Survival-Action-Klassikers.',
    price: 79.95,
    discountPrice: 59.95,
    image: 'images/service-2.jpg',
  },
  {
    id: 2,
    title: 'Hogwarts Legacy (PS5/Xbox/PC)',
    description: 'Open-World-Action-Rollenspiel in der Welt von Harry Potter.',
    price: 69.95,
    discountPrice: 54.95,
    image: 'images/service-3.jpg',
  },
  {
    id: 3,
    title: 'Resident Evil 4 Remake (PS5/PC)',
    description: 'Modernisierte Version des Survival-Horror-Klassikers.',
    price: 89.95,
    discountPrice: 74.95,
    image: 'images/service-4.jpg',
  },
  {
    id: 4,
    title: 'God of War Ragnarök (PS5)',
    description: 'Mythologisches Action-Epos mit atemberaubender Grafik und fesselnder Story.',
    price: 99.95,
    discountPrice: 84.95,
    image: 'images/service-5.jpg',
  },
  {
    id: 5,
    title: 'The Legend of Zelda: Tears of the Kingdom (Switch)',
    description: 'Heiß erwartete Fortsetzung mit neuen Mechaniken und Erkundungsmöglichkeiten.',
    price: 89.95,
    discountPrice: 69.95,
    image: 'images/service-6.jpg',
  },
]);
